name: "Zara Rahman"
description: "Zara's blog"

url: "http://zararah.net"
github.owner: "zararah"
twitter: "zararah"

paginate_path: "/blog/page:num/"
paginate: 10

permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

collections:
  category:
    output: true
    permalink: /blog/category/:path/
  projects:
    output: true
    permalink: /projects/:path/


plugins:
  - jekyll-paginate

excerpt_separator: "<!--more-->"
