name: "Zara Rahman"
description: "Zara's blog"

url: "http://zararah.net"
github.owner: "zararah"
twitter: "zararah"
pagine_path: "blog/page:num"
paginate: 10

markdown: rdiscount
permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"

collections:
  category:
    output: true
    permalink: /category/:path/

# gems:
#   - jekyll-redirect-from

excerpt_separator: "<!--more-->"